#!/bin/bash
set -e

LXD_USER=lxdadm
if [ "$USER" != "$LXD_USER"  ]; then
  exec su "$LXD_USER" "$0" -- "$@"
  # nothing is executed beyond that line, because
  # exec replaces running processes with the new one
fi

TMP_DIR=$(mktemp -d)
LXD_IMAGE_SERVER_HOST=lxd-image-server
LXD_IMAGE_OS=ubuntu
LXD_IMAGE_RELEASE=focal
LXD_IMAGE_ARCH=amd64
LXD_IMAGE_VARIANT=xfce
LXD_IMAGE_VERSION=$(date '+%Y%m%d_%H:%m')
LXD_IMAGE_PATH="$LXD_IMAGE_OS/$LXD_IMAGE_RELEASE/$LXD_IMAGE_ARCH/$LXD_IMAGE_VARIANT/$LXD_IMAGE_VERSION"

cd "$TMP_DIR"
mkdir -p "$LXD_IMAGE_PATH"

cd "$LXD_IMAGE_PATH"
sudo ~/go/bin/distrobuilder build-lxd /lxc-ci/images/"$LXD_IMAGE_OS".yaml \
    -o image.release="$LXD_IMAGE_RELEASE" \
    -o image.architecture="$LXD_IMAGE_ARCH" \
    -o image.variant="$LXD_IMAGE_VARIANT" \
    -o source.url="http://us.archive.ubuntu.com/ubuntu"
cd "$TMP_DIR"

scp -r "$LXD_IMAGE_PATH/lxd.tar.gz" $LXD_USER@$LXD_IMAGE_SERVER_HOST:/var/www/simplestreams/images/
scp -r "$LXD_IMAGE_PATH/rootfs.squashfs" $LXD_USER@$LXD_IMAGE_SERVER_HOST:/var/www/simplestreams/images/

cd /tmp
sudo rm -rf "$TMP_DIR"
