#!/bin/bash
set -e

#
# Usage:    update-image <os> <release> <arch> <variant>
#
LXD_USER=lxdadm
LXD_IMAGE_OS=$1
LXD_IMAGE_RELEASE=$2
LXD_IMAGE_ARCH=$3
LXD_IMAGE_VARIANT=$4

if [ "$USER" != "$LXD_USER"  ]; then
  exec su "$LXD_USER" "$0" "$LXD_IMAGE_OS" "$LXD_IMAGE_RELEASE" "$LXD_IMAGE_ARCH" "$LXD_IMAGE_VARIANT" -- "$@"
  # nothing is executed beyond that line, because
  # exec replaces running processes with the new one
fi

LXD_IMAGE_SERVER_HOST=lxd-image-server
LXD_IMAGE_VERSION=$(date '+%Y%m%d_%H:%M')
LXD_IMAGE_PATH="$LXD_IMAGE_OS/$LXD_IMAGE_RELEASE/$LXD_IMAGE_ARCH/$LXD_IMAGE_VARIANT/$LXD_IMAGE_VERSION"
TMP_DIR=$(mktemp -d)

cd /tmp
cd "$TMP_DIR"
mkdir -p "$LXD_IMAGE_PATH"

cd "$LXD_IMAGE_PATH"
echo "$LXD_IMAGE_PATH: Build..."

if [ "$LXD_IMAGE_OS" = "elementary" ]; then
    SUITE=${LXD_IMAGE_RELEASE}
    [ "${SUITE}" = "hera" ] && SUITE="bionic"
    [ "${SUITE}" = "odin" ] && SUITE="focal"

    sudo ~/go/bin/distrobuilder build-lxd /lxc-ci/images/"$LXD_IMAGE_OS".yaml \
        -o image.release="$LXD_IMAGE_RELEASE" \
        -o image.architecture="$ARCH" \
        -o image.variant="$LXD_IMAGE_VARIANT" \
        -o source.suite="$SUITE"

elif [ "$LXD_IMAGE_OS" = "fedora" ]; then
    ARCH=${LXD_IMAGE_ARCH}
    [ "${ARCH}" = "amd64" ] && ARCH="x86_64"

    sudo ~/go/bin/distrobuilder build-lxd /lxc-ci/images/"$LXD_IMAGE_OS".yaml \
        -o image.release="$LXD_IMAGE_RELEASE" \
        -o image.architecture="$ARCH" \
        -o image.variant="$LXD_IMAGE_VARIANT"

else
    sudo ~/go/bin/distrobuilder build-lxd /lxc-ci/images/"$LXD_IMAGE_OS".yaml \
        -o image.release="$LXD_IMAGE_RELEASE" \
        -o image.architecture="$LXD_IMAGE_ARCH" \
        -o image.variant="$LXD_IMAGE_VARIANT" \
        -o source.url="http://us.archive.ubuntu.com/ubuntu"
fi
cd "$TMP_DIR"

echo "$LXD_IMAGE_PATH: Upload..."
rsync -r "$TMP_DIR/"* $LXD_USER@$LXD_IMAGE_SERVER_HOST:"/var/www/simplestreams/images/"

cd /tmp
sudo rm -rf "$TMP_DIR"

echo "$LXD_IMAGE_PATH: Index..."
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
ssh $LXD_USER@$LXD_IMAGE_SERVER_HOST lxd-image-server update

echo "$LXD_IMAGE_PATH: Success."
